import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*; 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BeingMF
 */
public class InsertPage extends javax.swing.JFrame {
Connection con;  
PreparedStatement pst; 



    /**
     * Creates new form InsertPage
     */
    public InsertPage() {
        initComponents();
                try {
        
        setVisible(true);
        Class.forName("org.apache.derby.jdbc.ClientDriver"); //1.driver 
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/Life_Insurance","A","A"); //connection string
        JOptionPane.showMessageDialog(null,"DataBase Connected");
        pst=con.prepareStatement("insert into DATA values(?,?,?,?,?,?,?,?,?,?,?,?,?)"); //sql query 
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(InsertPage.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        M = new javax.swing.JTextField();
        B = new javax.swing.JComboBox<>();
        G = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        F = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        L = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        K = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        J = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        I = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        H = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        D = new javax.swing.JComboBox<>();
        AA = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        AAA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(M);
        M.setBounds(840, 470, 238, 34);

        B.setBackground(new java.awt.Color(0, 84, 166));
        B.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel1.add(B);
        B.setBounds(330, 260, 238, 30);
        jPanel1.add(G);
        G.setBounds(330, 470, 238, 35);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Policy Scheme");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 110, 150, 50);
        jPanel1.add(F);
        F.setBounds(330, 400, 238, 32);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Country");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 460, 90, 50);

        jButton1.setBackground(new java.awt.Color(0, 84, 166));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 610, 140, 44);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maritial Status");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 320, 170, 50);

        jButton2.setBackground(new java.awt.Color(0, 84, 166));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 610, 140, 44);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 460, 90, 50);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("I agree Term & Conditions");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(470, 540, 240, 31);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOB(mm/dd/yyyy)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 390, 200, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Full Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 180, 120, 50);
        jPanel1.add(A);
        A.setBounds(330, 190, 238, 34);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("State");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(630, 390, 74, 50);
        jPanel1.add(L);
        L.setBounds(840, 400, 238, 34);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pincode");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(630, 320, 90, 50);
        jPanel1.add(K);
        K.setBounds(840, 330, 238, 34);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("City");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(630, 250, 100, 50);
        jPanel1.add(J);
        J.setBounds(840, 260, 238, 34);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PAN No.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(630, 180, 100, 50);
        jPanel1.add(I);
        I.setBounds(840, 190, 238, 34);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Phone No.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(630, 110, 120, 50);
        jPanel1.add(H);
        H.setBounds(840, 120, 238, 34);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 250, 80, 50);

        D.setBackground(new java.awt.Color(0, 84, 166));
        D.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married", "Un Married" }));
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel1.add(D);
        D.setBounds(330, 330, 238, 30);

        AA.setBackground(new java.awt.Color(0, 84, 166));
        AA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home insurance", "Auto insurance", "Fire insurance", "Whole life policy", "Term life policy", "Endownment policy", "Pension plans" }));
        AA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AAActionPerformed(evt);
            }
        });
        jPanel1.add(AA);
        AA.setBounds(330, 120, 238, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/register.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-230, -40, 1480, 1140);
        jPanel1.add(AAA);
        AAA.setBounds(330, 72, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String id = AAA.getText();
        String policy = (String) AA.getSelectedItem();
        String name = A.getText();
        String gender = (String) B.getSelectedItem();
        String married = (String) D.getSelectedItem();
        String dob = F.getText();
        String email = G.getText();
        String phone = H.getText();
        String pan = I.getText();
        String city = J.getText();
        String pin = K.getText();
        String state = L.getText();
        String country= M.getText();

        try
        {
            pst.setString(1, id);
            pst.setString(2, policy);
            pst.setString(3,name);
            pst.setString(4,gender);
            pst.setString(5,married);
            pst.setString(6,dob);
            pst.setString(7,email);
            pst.setString(8,phone );
            pst.setString(9,pan);
            pst.setString(10,city);
            pst.setString(11,pin);
            pst.setString(12,state);
            pst.setString(13, country);

            int res=pst.executeUpdate();
            if(res>=1)
            {
                JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
                
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error Occurred");
            }
        }
        catch (HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void AAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InsertPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JComboBox<String> AA;
    private javax.swing.JTextField AAA;
    private javax.swing.JComboBox<String> B;
    private javax.swing.JComboBox<String> D;
    private javax.swing.JTextField F;
    private javax.swing.JTextField G;
    private javax.swing.JTextField H;
    private javax.swing.JTextField I;
    private javax.swing.JTextField J;
    private javax.swing.JTextField K;
    private javax.swing.JTextField L;
    private javax.swing.JTextField M;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class Int {

        public Int() {
        }
    }

    private static class Pension {

        public Pension() {
        }
    }
}
